### PR TITLE
Make about:processes work by implementing ProcInfo for Haiku

### LINKED ISSUE #62: ProcInfo_linux.cpp doesn't work
it utilize procfs which Haiku doesn't support

### PR DESCRIPTION
**Pull request by kenz-gelsoft**
Fixes https://github.com/kenz-gelsoft/gecko-dev/issues/62

### CODE REVIEW

File: toolkit/components/processtools/ProcInfo_haiku.cpp [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+      threadInfo.tid = thread.thread;
+      threadInfo.cpuTime = cpuTime;
+      info.threads.AppendElement(threadInfo);
+    }
+    
+    info.memory = 0;
+    ssize_t cookie_area = 0;
+    area_info area;
+    while (B_OK == get_next_area_info(team.team, &cookie_area, &area)) {
+      info.memory += area.size;
```
Comment (kenz-gelsoft) [inline toolkit/components/processtools/ProcInfo_haiku.cpp]: Collecting memory usage from team areas didnt work

Comment (kenz-gelsoft) [reply toolkit/components/processtools/ProcInfo_haiku.cpp]: use ram_size instead of size

File: toolkit/components/processtools/ProcInfo_haiku.cpp [hunk 2]
```diff
@@ -0,0 +1,99 @@
+/* -*- Mode: C++; tab-width: 8; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
+/* vim: set ts=8 sts=2 et sw=2 tw=80: */
+/* This Source Code Form is subject to the terms of the Mozilla Public
+ * License, v. 2.0. If a copy of the MPL was not distributed with this
+ * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
+
+#include "mozilla/ProcInfo.h"
+#include "mozilla/ProcInfo_linux.h"
```
Comment (kenz-gelsoft) [inline toolkit/components/processtools/ProcInfo_haiku.cpp]: We are based on linux variant, but this should be removed at the end.

File: toolkit/components/processtools/ProcInfo_haiku.cpp [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+#include "nsWhitespaceTokenizer.h"
+
+#include <cstdio>
+#include <cstring>
+#include <unistd.h>
+#include <dirent.h>
+
+#include <kernel/OS.h>
+
+#define NANOPERSEC 1000000000.
```
Comment (kenz-gelsoft) [inline toolkit/components/processtools/ProcInfo_haiku.cpp]: this wont be used too

File: toolkit/components/processtools/ProcInfo_haiku.cpp [hunk 4]
```diff
@@ -0,0 +1,99 @@
...
+    if (B_OK != get_team_info(request.pid, &team)) {
+      continue;
+    }
+
+    info.cpuTime = 0;
+    int32 cookie_thread = 0;
+    thread_info thread;
+    while (B_OK == get_next_thread_info(team.team, &cookie_thread, &thread)) {
+      const bigtime_t microseconds = thread.user_time + thread.kernel_time;
+      const uint64_t  cpuTime      = microseconds / 1000;
```
Comment (kenz-gelsoft) [inline toolkit/components/processtools/ProcInfo_haiku.cpp]: Cputime should be nanosec like other platforms

File: toolkit/components/processtools/ProcInfo_haiku.cpp [hunk 5]
```diff
@@ -0,0 +1,99 @@
...
+int GetCycleTimeFrequencyMHz() { return 0; }
+
+nsresult GetCpuTimeSinceProcessStartInMs(uint64_t* aResult) {
+  const thread_id thread = find_thread(NULL);
+  thread_info info;
+  if (B_OK != get_thread_info(thread, &info)) {
+    return NS_ERROR_FAILURE;
+  }
+  const bigtime_t microseconds = info.user_time + info.kernel_time;
+  *aResult = microseconds / 1000;
```
Comment (kenz-gelsoft) [inline toolkit/components/processtools/ProcInfo_haiku.cpp:21]: Maybe should use get_team_usage_info() like processcontroller

https://github.com/haiku/haiku/blob/master/src/apps/processcontroller/TeamBarMenuItem.cpp#L188

**Comment by kenz-gelsoft** [comment]
screenshot35

it works now
